(function(root){
 'use strict';
 function shuffle(items,rng=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 const toKata=text=>Array.from(text,c=>String.fromCharCode(c.charCodeAt(0)+96)).join('');
 function answers(sound,mode){return mode==='romaji'?sound.romaji:mode==='katakana'?sound.kanaAnswers.map(toKata):sound.kanaAnswers;}
 function question(sound,mode,collection,rng=Math.random){const accepted=answers(sound,mode),letters=[...new Set(accepted.join(''))],alphabet=mode==='romaji'?Array.from('abcdefghijklmnopqrstuvwxyz'):[...new Set(collection.flatMap(s=>Array.from(mode==='katakana'?s.katakana:s.hiragana)))];for(const c of shuffle(alphabet,rng)){if(letters.length>=10)break;if(!letters.includes(c))letters.push(c);}return {sound,mode,accepted,cards:shuffle(letters,rng),maxLength:Math.max(...accepted.map(s=>s.length))};}
 root.KanaListeningEngine={shuffle,answers,question,toKata};if(!root.document)return;
 const $=id=>document.getElementById(id),collection=root.KANA_SOUNDS||[],voices=root.KANA_AUDIO||{},player=$('player');const modes={hiragana:'Hiragana',katakana:'Katakana',romaji:'Romaji'},groups={basic:'Basic sound',voiced:'Voiced / P sound',combined:'Combined sound'};
 const state={mode:null,deck:[],index:0,score:0,skips:0,input:'',q:null,done:false,run:0};
 function show(id){for(const s of ['menu','game','result'])$(s).hidden=s!==id;}
 function stopAudio(){state.run++;player.pause();player.currentTime=0;}
 function play(){const run=++state.run;player.pause();player.currentTime=0;$('audio-status').className='audio-status';$('audio-status').textContent='Playing…';const promise=player.play();if(promise)promise.catch(()=>{if(run!==state.run||$('game').hidden)return;$('audio-status').className='audio-status error';$('audio-status').textContent='Tap Listen again to play the sound.';});}
 player.addEventListener('ended',()=>{if(!$('game').hidden)$('audio-status').textContent='Tap to listen again.';});player.addEventListener('error',()=>{if(!$('game').hidden){$('audio-status').className='audio-status error';$('audio-status').textContent='Audio unavailable. Tap Listen again to retry.';}});
 function start(mode){stopAudio();state.mode=mode;const set=$('sound-set').value,size=$('round-size').value;const pool=collection.filter(s=>set==='all'||s.category===set);state.deck=shuffle(pool).slice(0,size==='all'?pool.length:Number(size));state.index=0;state.score=0;state.skips=0;show('game');render();}
 function draw(){const n=Math.max(state.q.accepted[0].length,state.input.length);$('answer').replaceChildren();for(let i=0;i<n;i++){const span=document.createElement('span');span.className='answer-letter'+(state.input[i]?'':' empty');span.textContent=state.input[i]||'_';$('answer').append(span);}$('answer').setAttribute('aria-label',state.input?`Your answer: ${state.input}`:'Your answer is blank');$('check').disabled=!state.input||state.done;$('delete').disabled=!state.input||state.done;$('clear').disabled=!state.input||state.done;}
 function render(){stopAudio();state.q=question(state.deck[state.index],state.mode,collection);state.input='';state.done=false;$('mode-label').textContent=modes[state.mode];$('progress').textContent=`Question ${state.index+1} of ${state.deck.length}`;$('score').textContent=state.score;$('sound-group').textContent=groups[state.q.sound.category];$('reveal').hidden=true;$('feedback').textContent='';$('feedback').className='feedback';$('check').hidden=false;$('skip').hidden=false;$('cards').replaceChildren();for(const char of state.q.cards){const b=document.createElement('button');b.className='card';b.textContent=char;b.setAttribute('aria-label',`Letter ${char}`);b.addEventListener('click',()=>{if(state.done)return;if(state.input.length>=state.q.maxLength){$('feedback').textContent='Use Delete or Clear to change your answer.';return;}state.input+=char;$('feedback').textContent='';draw();});$('cards').append(b);}draw();player.src=voices[state.q.sound.id];$('instruction').focus({preventScroll:true});play();}
 function finish(correct){stopAudio();state.done=true;if(correct)state.score++;else state.skips++;$('score').textContent=state.score;$('feedback').className='feedback';$('feedback').textContent=correct?'Correct — well heard!':'Skipped. Listen again and learn this sound.';$('check').hidden=true;$('skip').hidden=true;for(const b of $('cards').children)b.disabled=true;draw();const s=state.q.sound;$('reveal-title').textContent=correct?'Here is the sound':'The answer';$('reveal-hira').textContent=s.hiragana;$('reveal-kata').textContent=s.katakana;$('reveal-romaji').textContent=s.romaji[0];$('spelling-note').textContent=s.kanaAnswers.length>1?`Same sound: ${s.kanaAnswers.join(' / ')}. Either kana spelling counts here.`:state.mode==='romaji'&&s.romaji.length>1?`Also accepted: ${s.romaji.slice(1).join(', ')}.`:'';$('reveal').hidden=false;$('next').textContent=state.index+1===state.deck.length?'See results →':'Next sound →';$('next').focus({preventScroll:true});}
 function check(){if(state.done||!state.input)return;if(state.q.accepted.includes(state.input))finish(true);else{$('feedback').className='feedback error';$('feedback').textContent='Not quite. Listen again, then edit your answer.';}}
 function menu(){stopAudio();show('menu');document.querySelector(`[data-mode="${state.mode}"]`).focus({preventScroll:true});}
 $('listen').addEventListener('click',play);$('check').addEventListener('click',check);$('skip').addEventListener('click',()=>{if(!state.done)finish(false);});$('delete').addEventListener('click',()=>{if(!state.done){state.input=state.input.slice(0,-1);$('feedback').textContent='';draw();}});$('clear').addEventListener('click',()=>{if(!state.done){state.input='';$('feedback').textContent='';draw();}});$('change-mode').addEventListener('click',menu);$('result-modes').addEventListener('click',menu);$('again').addEventListener('click',()=>start(state.mode));$('next').addEventListener('click',()=>{if(!state.done)return;stopAudio();state.index++;if(state.index<state.deck.length)render();else{show('result');$('result-title').textContent=`${state.score} / ${state.deck.length} correct`;$('result-copy').textContent=`${state.skips} skipped. Every listen is practice.`;$('result-title').focus({preventScroll:true});}});$('reload').addEventListener('click',()=>location.reload());
 const ready=collection.length===104&&collection.every(s=>voices[s.id]);if(ready){$('loading-status').hidden=true;for(const b of document.querySelectorAll('[data-mode]')){b.disabled=false;b.addEventListener('click',()=>start(b.dataset.mode));}}else{$('loading-status').textContent='Audio did not finish loading. Please reload.';$('reload').hidden=false;}
})(typeof window!=='undefined'?window:globalThis);
