(function(){
 'use strict';const $=id=>document.getElementById(id),words=window.SUSHI_WORDS,puzzles=window.SUSHI_CROSSWORDS;
 const state={mode:null,puzzle:null,selected:0,cell:0,filled:{},solved:new Set(),last:{}};
 const key=(r,c)=>`${r},${c}`;const cells=w=>Array.from(w.answer,(char,i)=>({char,key:key(w.row+(w.direction==='down'?i:0),w.col+(w.direction==='across'?i:0))}));
 const sushi=w=>words.find(s=>s.id===w.id);const image=w=>'../sushi-words/'+sushi(w).image;const clue=w=>state.mode==='ja'?sushi(w).en:sushi(w).ja;
 const direction=w=>w.direction==='across'?'横 / Across':'縦 / Down';
 function start(mode){state.mode=mode;const pool=puzzles[mode];let at=Math.floor(Math.random()*pool.length);if(at===state.last[mode])at=(at+1)%pool.length;state.last[mode]=at;state.puzzle=pool[at];state.filled={};state.solved=new Set();state.selected=0;state.cell=0;$('menu').hidden=true;$('game').hidden=false;$('finish').hidden=true;$('plates').replaceChildren();$('mode-label').textContent={ja:'ひらがな / Hiragana',en:'English',romaji:'Romaji'}[mode];drawBoard();select(0);}
 function drawBoard(){const p=state.puzzle,occupied=new Map(),numbers=new Map();for(const w of p.words){numbers.set(key(w.row,w.col),w.number);for(const c of cells(w))occupied.set(c.key,c.char);}$('board').replaceChildren();$('board').style.gridTemplateColumns=`repeat(${p.cols},44px)`;for(let r=0;r<p.rows;r++)for(let c=0;c<p.cols;c++){const k=key(r,c);if(!occupied.has(k)){const blank=document.createElement('span');blank.className='black';blank.setAttribute('aria-hidden','true');$('board').append(blank);continue;}const b=document.createElement('button');b.className='square';b.dataset.key=k;b.setAttribute('aria-label',`${r+1}行 ${c+1}列 / Row ${r+1}, column ${c+1}`);const small=document.createElement('small');small.textContent=numbers.get(k)||'';const char=document.createElement('span');char.className='square-letter';b.append(small,char);b.addEventListener('click',()=>{const matches=p.words.map((w,i)=>({i,at:cells(w).findIndex(x=>x.key===k)})).filter(x=>x.at>=0);const current=matches.findIndex(x=>x.i===state.selected);const chosen=matches.length>1&&current>=0?matches[(current+1)%matches.length]:matches[0];select(chosen.i,chosen.at);});$('board').append(b);}update();}
 function select(index,at){state.selected=index;const w=state.puzzle.words[index],cs=cells(w);state.cell=at===undefined?Math.max(0,cs.findIndex(c=>!state.filled[c.key])):at;$('clue-photo').src=image(w);$('clue-number').textContent=`${w.number} · ${direction(w)}`;$('clue-text').textContent=clue(w);$('clue-text').lang=state.mode==='ja'?'en':'ja';$('answer-size').textContent=`${w.answer.length} マス / letters`;$('feedback').textContent='';makeCards();update();reveal();}
 function makeCards(){const w=state.puzzle.words[state.selected],alphabet=state.mode==='ja'?'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわんがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽっゃゅょー':'ABCDEFGHIJKLMNOPQRSTUVWXYZ';const chars=[...new Set(w.answer)];while(chars.length<Math.max(10,new Set(w.answer).size)){const ch=alphabet[Math.floor(Math.random()*alphabet.length)];if(!chars.includes(ch))chars.push(ch);}for(let i=chars.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[chars[i],chars[j]]=[chars[j],chars[i]];}$('cards').replaceChildren();for(const char of chars){const b=document.createElement('button');b.className='card';b.textContent=char;b.addEventListener('click',()=>pick(char));$('cards').append(b);}}
 function update(){const p=state.puzzle,w=p.words[state.selected],cs=cells(w),active=cs[state.cell].key;for(const b of $('board').querySelectorAll('.square')){const k=b.dataset.key;b.querySelector('.square-letter').textContent=state.filled[k]||'';b.classList.toggle('active-word',cs.some(c=>c.key===k));b.classList.toggle('active-cell',k===active);b.classList.toggle('filled',!!state.filled[k]);b.classList.toggle('complete',p.words.some((word,i)=>state.solved.has(i)&&cells(word).some(c=>c.key===k)));b.setAttribute('aria-label',`${k.split(',').map(n=>Number(n)+1).join(',')} · ${state.filled[k]||'空欄 / blank'}${k===active?' · 選択中 / selected':''}`);}
 $('slots').replaceChildren();cs.forEach((c,i)=>{const b=document.createElement('button');b.className='slot'+(i===state.cell?' selected':'');b.textContent=state.filled[c.key]||'_';b.disabled=!!state.filled[c.key];b.setAttribute('aria-label',`${i+1}文字目 / Letter ${i+1}: ${state.filled[c.key]||'空欄 / blank'}`);b.addEventListener('click',()=>{state.cell=i;update();});$('slots').append(b);});for(const b of $('cards').children)b.disabled=state.solved.has(state.selected);
 $('plate-count').textContent=state.solved.size;$('progress').textContent=`${state.solved.size} / ${p.words.length} 完成 · words completed`;$('clue-list').replaceChildren();p.words.forEach((word,i)=>{const b=document.createElement('button');b.className='clue-item'+(i===state.selected?' selected':'')+(state.solved.has(i)?' solved':'');const photo=document.createElement('img');photo.src=image(word);photo.alt='';const label=document.createElement('span');label.textContent=`${word.number} · ${clue(word)}${state.solved.has(i)?' ✓':''}`;const sub=document.createElement('small');sub.textContent=`${direction(word)} · ${word.answer.length}マス`;label.append(sub);b.append(photo,label);b.addEventListener('click',()=>select(i));$('clue-list').append(b);});}
 function reveal(){for(const [container,element] of [[document.querySelector('.board-scroll'),document.querySelector('.active-cell')],[$('slots'),document.querySelector('.slot.selected')]]){if(!element)continue;const a=container.getBoundingClientRect(),b=element.getBoundingClientRect();if(b.left<a.left+6)container.scrollLeft+=b.left-a.left-6;else if(b.right>a.right-6)container.scrollLeft+=b.right-a.right+6;if(b.top<a.top+6)container.scrollTop+=b.top-a.top-6;else if(b.bottom>a.bottom-6)container.scrollTop+=b.bottom-a.bottom+6;}}
 function pick(char){const w=state.puzzle.words[state.selected];if(state.solved.has(state.selected))return;const cs=cells(w),c=cs[state.cell];if(state.filled[c.key]){state.cell=cs.findIndex(x=>!state.filled[x.key]);if(state.cell<0)return;}const target=cs[state.cell];if(char!==target.char){$('feedback').textContent='もう一度、ヒントを見てみよう。 / Try another letter.';$('feedback').className='feedback error';return;}state.filled[target.key]=char;let completed=0;state.puzzle.words.forEach((word,i)=>{if(!state.solved.has(i)&&cells(word).every(c=>state.filled[c.key]===c.char)){state.solved.add(i);const plate=document.createElement('span');plate.className='plate';$('plates').append(plate);completed++;}});const next=cs.findIndex(c=>!state.filled[c.key]);state.cell=next>=0?next:state.cell;$('feedback').className='feedback';$('feedback').textContent=completed?'ことばが完成。皿が増えました。 / A word complete. Another plate!':'正しい文字です。 / Correct letter.';update();reveal();if(state.solved.size===state.puzzle.words.length){$('finish').hidden=false;$('finish-title').textContent=`${state.solved.size}皿、クロスワード完成！ / Puzzle complete!`;$('finish-title').focus({preventScroll:true});$('finish').scrollIntoView({block:'nearest'});}}
 function move(delta){const n=state.puzzle.words.length;for(let d=1;d<=n;d++){const i=(state.selected+delta*d+n*2)%n;if(!state.solved.has(i)){select(i);return;}}select((state.selected+delta+n)%n);}
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('previous-word').addEventListener('click',()=>move(-1));$('next-word').addEventListener('click',()=>move(1));$('again').addEventListener('click',()=>start(state.mode));$('change-mode').addEventListener('click',()=>{$('game').hidden=true;$('menu').hidden=false;document.querySelector(`[data-mode="${state.mode}"]`).focus({preventScroll:true});});
})();
